import 'package:flutter/material.dart';

// class Messages {
//   final Key? key;
//   final  message;
//   final  userName;
//   final  userImage;
//   final  urlImage;
//   final  isMe;
//   final TimeSent;
//   final String urlVoice;
//   final isTyping;
//   final id;
//   final selected;
//   final isReplied;
//   Messages( {
//     this.key,
//     required this.id,
//     required this.message,
//     required this.userName,
//     required this.userImage,
//     required this.urlImage,
//     required this.isMe,
//     required this.TimeSent,
//     required this.urlVoice,
//     required this.selected,
//     required this.isTyping,
//     required this.isReplied,
//   });
// }


class Autogenerated {
  String? command;
  List<Messages>? messages;

  Autogenerated({this.command, this.messages});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    command = json['command'];
    if (json['messages'] != null) {
      messages =  <Messages>[];
      json['messages'].forEach((v) {
        messages!.add(new Messages.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['command'] = this.command;
    if (this.messages != null) {
      data['messages'] = this.messages!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Messages {
  int? id;
  int? authorId;
  String? text;
  var reaction;
  var image;
  var voiceRecord;
  String? createdAt;
  String? updatedAt;
  int? chat;
  var selected;

  Messages(
      {this.id,
        this.authorId,
        this.text,
        this.reaction,
        this.image,
        this.voiceRecord,
        this.createdAt,
        this.updatedAt,
        this.chat,this.selected});

  Messages.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    authorId = json['author_id'];
    text = json['text'];
    reaction = json['reaction'];
    image = json['image'];
    voiceRecord = json['voice_record'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    chat = json['chat'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['author_id'] = this.authorId;
    data['text'] = this.text;
    data['reaction'] = this.reaction;
    data['image'] = this.image;
    data['voice_record'] = this.voiceRecord;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['chat'] = this.chat;
    return data;
  }
}
